
* Make a fun game!
** Performance
*** The game must run at a consistent frame rate at all times, 60 fps would be preferable.
** Level Editor
*** Level
**** When you create a new level it asks for the level speed.  Then when you create things that should have the appearance of moving with the background, it will default to this speed.
**** TODO How is time recorded, what is the needed granularity, should time match frames? Would need to make time dependant of the fps then.
*** There must be an easy way of creating levels as well as enemy flight and attack patterns.
**** Enemies should follow a specific path then exit the screen.  Enemies will often follow the same path so it is necessary that these paths can be reused.
***** A starting point for this path must be on the border of a screen, enemies cannot appear in the middle of the screen.
***** The ending point must also be at the border of the screen.
***** The path should be any curve that has one starting and ending point.
***** TODO What about something like a circle where the enemy should fly around the cirle 5 times?
**** Enemies should be able to perform specific actions along the path they follow.
***** Enemies should be able to shoot different types of bullets.
***** The creator should be able to set the (at least initial) speed that the enemy travels along the path.
***** [#C] The enemy should be able to change speeds along the path.
***** There will likely be additional actions that will need to be implemented.
**** Complete enemy paths and actions should be able to be copied with the only difference being the time they start the motion in the level.
** Main Game
*** The Player
**** The player is represented by the players finger.
**** The player can move.
***** Since the player is represented by the player's finger, when the finger is moved the player moves.
**** The player can shoot a steady stream of LASERS.
***** By holding down a button (default bottom left of the screen? configurable.) The player spawns player bullets at his location.
**** Player Cloaking
***** If a player lifts his finger off the screen he can no longer move but is invincible.
***** Possibly the player can warp, instead of having to put there finger back in the same place, they can set it somewhere else to warp the player.
****** When you are invisible enemies can still target you so if tons of guys are shooting at your old pos it might be impossible to come back without warping.
****** Create a meter that has your cloaking time allowed?  It recharges by killing enemies, when its out you cannot warp.
***** The field the player can warp to will be a semitransparent circle with the center being the player.
***** There should be a meter displayed (probably on the right side of the screen).
***** The meter will show how far the player can warp. The farther they warp the more energy it takes up.
***** If the meter is completely empty than lifting your finger off the screen kills you.
****** I am not sure about this point, perhaps it makes the player visible agian.
***** Killing enemies will give the player more points to his meter.  The enemy will contain how much point bonus it gives.
**** Maybe do some callabration at the beginning to determine player finger size, so can make a tight fitting bounding box.
**** Player lives
***** If the player gets hit a life is lost.
***** A player has X lives.  When all lives are lost the game is over.
***** When a player dies they revive at the point the player puts his finger back on the screen.
****** TODO Must decide the user experience for letting the player know to release the screen and touch somewhere else.
*** Scoring
**** The player gets points for killing enemies.
**** Possible online scoreboard.
*** Levels
**** When a level is unlocked a player can jump to it from the main menu.
**** Time
***** When a level starts a timer starts that is used to determine when different events happen.
***** Enemies enter the level at a given time and act out their actions using the absolute coords written by the level editor.
**** An image in the background begins scrolling and continues scrolling down at a constant speed.
***** TODO Image can either wrap, end during boss fight, or continue until the level must end (time limit).

*** Menus
**** The main menu will have the following options.
***** Play
***** Options
****** Allow player to move position of shoot button.
****** Adjust starting lives.
******* Gives point penalty.
*** Enemies
**** Enemies are not mapped on to the level's relative position
enemies enter levelr at a given time. and follow the path mapped out for them in absolute coords.  Hazards are also given a speed so although it looks like its scrolling down with the level its actually moving dows
**** TODO Exploding enemies?
*** Enemy Bullets
**** Normal Bullets
***** When these are created it looks where the player is currently and shoots in a line towards that position with a given speed.
**** Homing
***** These bullets will home in on the player.
***** TODO How exactly will this home.  Tricky.
*** Hazards
**** There can be lasers!!
***** The lasers are basically a line segment that will kill the player upon contact.
*** Player bullets
**** Player bullets are unlimited.
**** They can be shot at rapid fire so it basically makes a solid line of fire.
**** TODO I feel like there needs to be some balance to this to make it so there is a penalty of some kind for shooting so many bullets.

* Risks
** The player finger must track the player sprite very closely or the player will get killed unfairly  - 
*** DONE Resolution - build a prototype to determine if this will be a showstopper.
    Seems to me that a player cannot move their finger rapidly across the screen and avoid many enemies so this should be a non issue.
