* Vision
  Animation should make the hamsters come alive, attention to detail
* The game
** Non-functional Requirements
*** Performance
**** The game must run at a consistent frame rate at all times, 60 fps would be preferable, but 30 or 40 should be fine.
*** Responsiveness
**** The game must be able to shutdown and save state quickly.
***** TODO Look to see if Apple has regulations on shutdown time. 	   :TBD:
***** The shutdown needs to happen as quickly as possible.  Target of under a second.
***** On shutdown, if game is in progress [[Quicksave][Quicksave]].
*** Stability
**** The game should ship with no known crashes.
**** If there are smaller bugs found a judgement call should be made whether they should be fixed before sending to store.
** Functional Requirements
*** Main Game
**** Orientation
**** Player Actions
***** Pet
****** Player can swipe opposite direction of hamster slowly to pet
***** Whack
****** Swipe fast at hamster to send him flying
***** Attract
****** If you put your finger on the screen without moving the hamster will come up to it and lick
***** Nudge
****** If you put your finger behind hamster and slowly move it, it will nudge the hamster in that direction
***** Repel
****** Generally the hamster will move away from your finger
***** Pin
****** If you put your finger directly on a hamster it pins them where they are until you remove your finger
***** Tilt
****** If you tilt the screen all the hamsters will go tumbling down the plane
***** Pinch
****** If you pinch your fingers together over a hamster it will pick them up until one of your fingers moves away from the other
**** Hamsters
***** Creation
****** When you get a new hamster you can name them.
***** Mood
****** Love
******* This will be determined by feeding, petting, not doing mean things
***** Food
****** You can pull food out of the [[items menu][items menu]] and drag it on the screen.
******* Where your finger releases the screen is where the food will be dropped.
****** Hamsters will have a hunger meter.
******* Hamsters are attracted to food, the amount of attraction is affected by this meter.
******* Different foods will fill this meter to different degrees.
******* Hamsters will [[Death][die]] if this meter runs out.
***** Toys
****** You can place a hampster wheel which the hampster will run on.
***** Menus
****** Items <<items menu>>
******* From this menu you can select food or entertainment to place on the screen
****** Stats
******* From this menu, you can look at the hamster's name and its various stats

***** Death <<Death>>
****** When the hamster dies it will create a tombstone that will fade eventually.
****** Other hamsters will give your hamster a funeral and mourn.
****** If you have zero left, you get a new one.
**** Scoring
**** Menus
**** QuickSave <<Quicksave>>
***** The player may need to shut down this game fast for a phone call or life interrupting in some fashion.
* Risks
* Events and Responses
** Phone Call Comes In
*** QuickSave
